### ISSUE TITLE
Highlight Whole Row on Mouseover

### ISSUE THREAD

**Issue by codeBelt** [glideapps/glide-data-grid#437]
Is there a way to highlight the whole row when rolling over one row item? I know the whole roll can be highlighted when you check the checkbox `rowMarkers={'checkbox'}` but I would like to do it when hovering over a row.

Also, how do I show the pointer cursor when hovering over rows?

Example from our current MUI table:
![animation](https://user-images.githubusercontent.com/2893563/179084774-ed140313-49b3-4e38-ab8f-203269c8857a.gif)

Thanks, Awesome library!

**Comment by codeBelt** [comment]
I see there is `getRowThemeOverride`... Maybe there is a way to tell when the mouse is over a row and we can change the color. 🤷

**Comment by jassmith** [comment]
In the event there are no row-markers you need to set x to 0 instead of -1 and don't add one to your column count. Effectively the row markers are a -1 column we are also highlighting with this range.

**Comment by codeBelt** [comment]
Oh awesome, I will try tomorrow. Thanks!

**Comment by jassmith** [comment]
will investigate, I will say your stack trace is strange, can you post the full thing

**Comment by codeBelt** [comment]
Here is an example where it breaks: https://codesandbox.io/s/glidedatagrid-highlightregions-rowmarkers-error-tiuvjw?file=/components/DataGrid.tsx

Here is the stack track from my app:
```
index.js?b89e:1530 Uncaught TypeError: Cannot read properties of undefined (reading 'width')
    at computeBounds (index.js?b89e:1530:1)
    at eval (index.js?b89e:3984:1)
    at Array.map (<anonymous>)
    at drawHighlightRings (index.js?b89e:3974:1)
    at drawGrid (index.js?b89e:4305:1)
    at DataGrid.react__WEBPACK_IMPORTED_MODULE_0__.useCallback._d (index.js?b89e:4843:1)
    at eval (index.js?b89e:4885:1)
    at commitHookEffectListMount (react-dom.development.js?ac89:20573:1)
    at commitLifeCycles (react-dom.development.js?ac89:20634:1)
    at commitLayoutEffects (react-dom.development.js?ac89:23426:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js?ac89:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?ac89:3994:1)
    at invokeGuardedCallback (react-dom.development.js?ac89:4056:1)
    at commitRootImpl (react-dom.development.js?ac89:23151:1)
    at unstable_runWithPriority (scheduler.development.js?bcd2:468:1)
    at runWithPriority$1 (react-dom.development.js?ac89:11276:1)
    at commitRoot (react-dom.development.js?ac89:22990:1)
    at performSyncWorkOnRoot (react-dom.development.js?ac89:22329:1)
    at eval (react-dom.development.js?ac89:11327:1)
    at unstable_runWithPriority (scheduler.development.js?bcd2:468:1)
    at runWithPriority$1 (react-dom.development.js?ac89:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js?ac89:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js?ac89:11309:1)
    at scheduleUpdateOnFiber (react-dom.development.js?ac89:21893:1)
    at dispatchAction (react-dom.development.js?ac89:16139:1)
    at eval (UiTable.tsx?7b06:30:5)
    at eval (index.js?b89e:8339:1)
    at eval (index.js?b89e:5541:1)
    at eval (index.js?b89e:5091:1)
    at eventListener (index.js?b89e:663:1)
computeBounds @ index.js?b89e:1530
eval @ index.js?b89e:3984
drawHighlightRings @ index.js?b89e:3974
drawGrid @ index.js?b89e:4305
DataGrid.react__WEBPACK_IMPORTED_MODULE_0__.useCallback._d @ index.js?b89e:4843
eval @ index.js?b89e:4885
commitHookEffectListMount @ react-dom.development.js?ac89:20573
commitLifeCycles @ react-dom.development.js?ac89:20634
commitLayoutEffects @ react-dom.development.js?ac89:23426
callCallback @ react-dom.development.js?ac89:3945
invokeGuardedCallbackDev @ react-dom.development.js?ac89:3994
invokeGuardedCallback @ react-dom.development.js?ac89:4056
commitRootImpl @ react-dom.development.js?ac89:23151
unstable_runWithPriority @ scheduler.development.js?bcd2:468
runWithPriority$1 @ react-dom.development.js?ac89:11276
commitRoot @ react-dom.development.js?ac89:22990
performSyncWorkOnRoot @ react-dom.development.js?ac89:22329
eval @ react-dom.development.js?ac89:11327
unstable_runWithPriority @ scheduler.development.js?bcd2:468
runWithPriority$1 @ react-dom.development.js?ac89:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?ac89:11322
flushSyncCallbackQueue @ react-dom.development.js?ac89:11309
scheduleUpdateOnFiber @ react-dom.development.js?ac89:21893
dispatchAction @ react-dom.development.js?ac89:16139
eval @ UiTable.tsx?7b06:30
eval @ index.js?b89e:8339
eval @ index.js?b89e:5541
eval @ index.js?b89e:5091
eventListener @ index.js?b89e:663
next-dev.js?3515:25 The above error occurred in the <ForwardRef(DataGrid)> component:

    at DataGrid (webpack-internal:///./node_modules/@glideapps/glide-data-grid/dist/js/index.js:4606:5)
    at DataGridDnd (webpack-internal:///./node_modules/@glideapps/glide-data-grid/dist/js/index.js:5555:84)
    at div
    at div
    at render (webpack-internal:///./node_modules/@glideapps/glide-data-grid/dist/js/index.js:151:13)
    at div
    at AutoSizer (webpack-internal:///./node_modules/react-virtualized-auto-sizer/dist/index.esm.js:355:5)
    at div
    at InfiniteScroller (webpack-internal:///./node_modules/@glideapps/glide-data-grid/dist/js/index.js:5830:5)
    at GridScroller (webpack-internal:///./node_modules/@glideapps/glide-data-grid/dist/js/index.js:6020:5)
    at DataGridSearch (webpack-internal:///./node_modules/@glideapps/glide-data-grid/dist/js/index.js:6299:5)
    at div
    at render (webpack-internal:///./node_modules/@glideapps/glide-data-grid/dist/js/index.js:151:13)
    at DataEditorContainer (webpack-internal:///./node_modules/@glideapps/glide-data-grid/dist/js/index.js:7290:5)
    at DataEditorImpl (webpack-internal:///./node_modules/@glideapps/glide-data-grid/dist/js/index.js:7356:90)
    at UiTable (webpack-internal:///./src/components/ui/ui-table/UiTable.tsx:125:25)
    at LoadableImpl (webpack-internal:///./node_modules/next/dist/shared/lib/loadable.js:101:38)
    at observerComponent (webpack-internal:///./node_modules/mobx-react-lite/es/observer.js:50:73)
    at LocalStoreProvider (webpack-internal:///./src/components/shared/local-store-provider/LocalStoreProvider.tsx:16:22)
    at observerComponent (webpack-internal:///./node_modules/mobx-react-lite/es/observer.js:50:73)
    at observerComponent (webpack-internal:///./node_modules/mobx-react-lite/es/observer.js:50:73)
    at observerComponent (webpack-internal:///./node_modules/mobx-react-lite/es/observer.js:50:73)
    at main
    at div
    at observerComponent (webpack-internal:///./node_modules/mobx-react-lite/es/observer.js:50:73)
    at PortalProvider (webpack-internal:///./src/components/shared/portals/portals.tsx:46:62)
    at InnerThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:21:70)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:47:5)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:41:5)
    at StyledEngineProvider (webpack-internal:///./node_modules/@mui/styled-engine/StyledEngineProvider/StyledEngineProvider.js:26:5)
    at MuiStylesAndThemeProvider (webpack-internal:///./src/components/ui/theme/MuiStylesAndThemeProvider.tsx:29:23)
    at NextApp (webpack-internal:///./src/pages/_app.tsx:110:53)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20746)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23395)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:323:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:844:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:968:27)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
window.console.error @ next-dev.js?3515:25
overrideMethod @ react_devtools_backend.js:4026
e.<computed> @ 45e178c4b8ad1dd781c9.js:2
logCapturedError @ react-dom.development.js?ac89:20085
callback @ react-dom.development.js?ac89:20154
callCallback @ react-dom.development.js?ac89:12318
commitUpdateQueue @ react-dom.development.js?ac89:12339
commitLifeCycles @ react-dom.development.js?ac89:20709
commitLayoutEffects @ react-dom.development.js?ac89:23426
callCallback @ react-dom.development.js?ac89:3945
invokeGuardedCallbackDev @ react-dom.development.js?ac89:3994
invokeGuardedCallback @ react-dom.development.js?ac89:4056
commitRootImpl @ react-dom.development.js?ac89:23151
unstable_runWithPriority @ scheduler.development.js?bcd2:468
runWithPriority$1 @ react-dom.development.js?ac89:11276
commitRoot @ react-dom.development.js?ac89:22990
performSyncWorkOnRoot @ react-dom.development.js?ac89:22329
eval @ react-dom.development.js?ac89:11327
unstable_runWithPriority @ scheduler.development.js?bcd2:468
runWithPriority$1 @ react-dom.development.js?ac89:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?ac89:11322
flushSyncCallbackQueue @ react-dom.development.js?ac89:11309
scheduleUpdateOnFiber @ react-dom.development.js?ac89:21893
dispatchAction @ react-dom.development.js?ac89:16139
eval @ UiTable.tsx?7b06:30
eval @ index.js?b89e:8339
eval @ index.js?b89e:5541
eval @ index.js?b89e:5091
eventListener @ index.js?b89e:663
next-dev.js?3515:25 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at DataGrid (webpack-internal:///./node_modules/@glideapps/glide-data-grid/dist/js/index.js:4606:5)
    at DataGridDnd (webpack-internal:///./node_modules/@glideapps/glide-data-grid/dist/js/index.js:5555:84)
    at div
    at div
    at render (webpack-internal:///./node_modules/@glideapps/glide-data-grid/dist/js/index.js:151:13)
    at div
    at AutoSizer (webpack-internal:///./node_modules/react-virtualized-auto-sizer/dist/index.esm.js:355:5)
    at div
    at InfiniteScroller (webpack-internal:///./node_modules/@glideapps/glide-data-grid/dist/js/index.js:5830:5)
    at GridScroller (webpack-internal:///./node_modules/@glideapps/glide-data-grid/dist/js/index.js:6020:5)
    at DataGridSearch (webpack-internal:///./node_modules/@glideapps/glide-data-grid/dist/js/index.js:6299:5)
    at div
    at render (webpack-internal:///./node_modules/@glideapps/glide-data-grid/dist/js/index.js:151:13)
    at DataEditorContainer (webpack-internal:///./node_modules/@glideapps/glide-data-grid/dist/js/index.js:7290:5)
    at DataEditorImpl (webpack-internal:///./node_modules/@glideapps/glide-data-grid/dist/js/index.js:7356:90)
    at UiTable (webpack-internal:///./src/components/ui/ui-table/UiTable.tsx:125:25)
    at LoadableImpl (webpack-internal:///./node_modules/next/dist/shared/lib/loadable.js:101:38)
    at observerComponent (webpack-internal:///./node_modules/mobx-react-lite/es/observer.js:50:73)
    at LocalStoreProvider (webpack-internal:///./src/components/shared/local-store-provider/LocalStoreProvider.tsx:16:22)
    at observerComponent (webpack-internal:///./node_modules/mobx-react-lite/es/observer.js:50:73)
    at observerComponent (webpack-internal:///./node_modules/mobx-react-lite/es/observer.js:50:73)
    at observerComponent (webpack-internal:///./node_modules/mobx-react-lite/es/observer.js:50:73)
    at main
    at div
    at observerComponent (webpack-internal:///./node_modules/mobx-react-lite/es/observer.js:50:73)
    at PortalProvider (webpack-internal:///./src/components/shared/portals/portals.tsx:46:62)
    at InnerThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:21:70)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:47:5)
    at ThemeProvider (webpack-internal:///./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:41:5)
    at StyledEngineProvider (webpack-internal:///./node_modules/@mui/styled-engine/StyledEngineProvider/StyledEngineProvider.js:26:5)
    at MuiStylesAndThemeProvider (webpack-internal:///./src/components/ui/theme/MuiStylesAndThemeProvider.tsx:29:23)
    at NextApp (webpack-internal:///./src/pages/_app.tsx:110:53)
window.console.error @ next-dev.js?3515:25
overrideMethod @ react_devtools_backend.js:4026
e.<computed> @ 45e178c4b8ad1dd781c9.js:2
printWarning @ react-dom.development.js?ac89:67
error @ react-dom.development.js?ac89:43
warnAboutUpdateOnUnmountedFiberInDEV @ react-dom.development.js?ac89:23914
scheduleUpdateOnFiber @ react-dom.development.js?ac89:21840
dispatchAction @ react-dom.development.js?ac89:16139
eval @ index.js?b89e:5092
eventListener @ index.js?b89e:663
45e178c4b8ad1dd781c9.js:2 [Fast Refresh] rebuilding
45e178c4b8ad1dd781c9.js:2 [Fast Refresh] rebuilding


```

**Comment by jassmith** [comment]
`width: initialIndexes.length,` should read `width: initialColumns.length,`

**Comment by jassmith** [comment]
I've updated the demo with an even simpler version.

**Comment by jassmith** [comment]
Note that the updated version 100% deps on 5.0.0 or it wont redraw correctly. The rowThemeOverride previously did not force a blitless draw. I made it do that.

**Comment by codeBelt** [comment]
@jassmith never mind about the high light not working because I needed the latest and greatest version of v5.

But any insight into having the pointer cursor would be greatly appreciated.

**Comment by jassmith** [comment]
There cells can be provided with a cursorOverride in v5.

**Comment by codeBelt** [comment]
@jassmith I have another request... Can you make it so we can disable row cell section and column highlight? We would like the table to be plain and only show the mouseover highlight and not the selection of the cell that was clicked on.

I was able to get close but changing the theme (`accentColor`, `accentLight`, and `bgHeaderHasFocus`) properties but it would be nice to have the ability to disable cell select and the column highlight.

![animation](https://user-images.githubusercontent.com/2893563/179788781-a47b9b83-9a8f-46b9-90d5-1961cfaa0c97.gif)

**Comment by jassmith** [comment]
```tsx
const e = React.useMemo(() => ({
  current: undefined,
  rows: CompactSelection.empty();
  columns: CompactSelection.empty();
}, []);

<DataEditor {...otherProps} selection={e} />
```

**Comment by jassmith** [comment]
This forces the grid to always have an empty selection, which means it will never show thigns as selected
